require("../node_modules/jquery/dist/jquery.slim.min");
require("../node_modules/@popperjs/core/dist/umd/popper.min");
require("../node_modules/bootstrap/dist/js/bootstrap.bundle.min");
require("../scss/custom-bootstrap.scss");
// require("../assets/iconsax-css/style.css");
// require("../node_modules/boxicons/fonts/boxicons.eot");
// require("../node_modules/boxicons/fonts/boxicons.svg");
// require("../node_modules/boxicons/fonts/boxicons.ttf");
// require("../node_modules/boxicons/fonts/boxicons.woff");
// require("../node_modules/boxicons/fonts/boxicons.woff2");
